routes/web.php
        return view('admin/500');
    });

    # Lock screen
    Route::get('{id}/lockscreen', 'UsersController@lockscreen')->name('lockscreen');
    Route::post('{id}/lockscreen', 'UsersController@postLockscreen')->name('lockscreen');
    # All basic routes defined here
    Route::get('login', 'AuthController@getSignin')->name('login');
    Route::get('signin', 'AuthController@getSignin')->name('signin');
    Route::post('signin', 'AuthController@postSignin')->name('postSignin');
    Route::post('signup', 'AuthController@postSignup')->name('admin.signup');
    Route::post('forgot-password', 'AuthController@postForgotPassword')->name('forgot-password');

    # Forgot Password Confirmation
    Route::get('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm')->name('forgot-password-confirm');
    Route::post('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm');

    #Update Permit Status -> Dalam Pengurusan Permit
    Route::get('update-permit/{npm}/{noPermit}', 'PermitController@getUpdatePermitConfirm')->name('update-permit-confirm');

    # Logout
    Route::get('logout', 'AuthController@getLogout')->name('logout');

    # Account Activation
    Route::get('activate/{userId}/{activationCode}', 'AuthController@getActivate')->name('activate');
});


Route::group(['prefix' => 'admin',  'as' => 'admin.'], function () {
    # Dashboard / Index
    Route::get('/dashboard', 'JoshController@showHome')->name('dashboard');

});

Route::group(['prefix' => 'admin','namespace'=>'Admin', 'as' => 'admin.'], function () {
    
    Route::group(['middleware' => 'superadmin'], function () {

        # User Management
        Route::group([ 'prefix' => 'users'], function () {
            Route::get('data', 'UsersController@data')->name('users.data');
            Route::get('{user}/delete', 'UsersController@destroy')->name('users.delete');
            Route::get('{user}/confirm-delete', 'UsersController@getModalDelete')->name('users.confirm-delete');
            Route::get('{user}/restore', 'UsersController@getRestore')->name('restore.user');
            Route::post('{user}/passwordreset', 'UsersController@passwordreset')->name('passwordreset');
            Route::post('passwordreset', 'UsersController@passwordreset')->name('passwordreset');

        });
        Route::resource('users', 'UsersController');

        Route::get('deleted_users',['before' => 'Sentinel', 'uses' => 'UsersController@getDeletedUsers'])->name('deleted_users');

        # Group Management
        Route::group(['prefix' => 'groups'], function () {
            Route::get('{group}/delete', 'GroupsController@destroy')->name('groups.delete');
            Route::get('{group}/confirm-delete', 'GroupsController@getModalDelete')->name('groups.confirm-delete');
            Route::get('{group}/restore', 'GroupsController@getRestore')->name('groups.restore');
        });
        Route::resource('groups', 'GroupsController');

        # Master Bidang
        Route::group([ 'prefix' => 'bidang'], function () {
            Route::get('data', 'BidangController@data')->name('bidang.data');
            Route::get('{bidang}/delete', 'BidangController@destroy')->name('bidang.delete');
        });
        Route::resource('bidang', 'BidangController');
        
        # Master Subbidang
        Route::group([ 'prefix' => 'subbidang'], function () {
            Route::get('data', 'SubbidangController@data')->name('subbidang.data');
            Route::get('{subbidang}/delete', 'SubbidangController@destroy')->name('subbidang.delete');
        });
        Route::resource('subbidang', 'SubbidangController');
        
        # Master Unit
        Route::group([ 'prefix' => 'unit'], function () {
            Route::get('data', 'UnitController@data')->name('unit.data');
            Route::get('{unit}/delete', 'UnitController@destroy')->name('unit.delete');
        });
        Route::resource('unit', 'UnitController');
        


    });
Route::resource('users', 'UsersController');

// Route::group(['middleware' => ['superadmin']], function () {   // Diedit 15-04-2020
    # Laporan Kerjasama
    Route::group([ 'prefix' => 'laporan_kerma'], function () {
        Route::get('data', 'LaporanKermaController@data')->name('laporan_kerma.data');
        Route::get('{laporan_kerma}/delete', 'LaporanKermaController@destroy')->name('laporan_kerma.delete');
        Route::get('data_laporan/{tahun}/{bulan}/{negara}', 'LaporanKermaController@dataLaporan')->name('laporan_kerma.dataLaporan');
        Route::post('data_laporan', 'LaporanKermaController@cetakLaporan')->name('laporan_kerma.cetakLaporan');
    });
    Route::resource('laporan_kerma', 'LaporanKermaController');    

    # Laporan Mahasiswa
    Route::group([ 'prefix' => 'laporan_mahasiswa'], function () {
        Route::get('data', 'LaporanMahasiswaController@data')->name('laporan_mahasiswa.data');
        Route::get('{laporan_mahasiswa}/delete', 'LaporanMahasiswaController@destroy')->name('laporan_mahasiswa.delete');
        Route::get('data_laporan/{tahun}/{bulan}/{negara}', 'LaporanMahasiswaController@dataLaporan')->name('laporan_mahasiswa.dataLaporan');
        Route::post('data_laporan', 'LaporanMahasiswaController@cetakLaporan')->name('laporan_mahasiswa.cetakLaporan');
    });
    Route::resource('laporan_mahasiswa', 'LaporanMahasiswaController');
// });

    # Permit
    Route::group([ 'prefix' => 'permit'], function () {
        Route::get('data', 'PermitController@data')->name('permit.data');
        Route::get('get_mahasiswa/{npm}', 'PermitController@getMahasiswa')->name('permit.get_mahasiswa');
        Route::get('{permit}/delete', 'PermitController@destroy')->name('permit.delete');
        Route::get('ambilFile/{permit}', 'PermitController@ambilFile')->name('permit.ambilFile');
        Route::get('data_status/{status}', 'PermitController@data_status')->name('permit.data_status');

    });
    Route::resource('permit', 'PermitController');
    
    # Kerjasama
    Route::group([ 'prefix' => 'kerma'], function () {
        Route::get('data', 'KermaController@data')->name('kerma.data');
        Route::get('data_status/{status}', 'KermaController@data_status')->name('kerma.data_status');
        Route::get('{kerma}/delete', 'KermaController@destroy')->name('kerma.delete');
        Route::get('ambilFile/{kerma}', 'KermaController@ambilFile')->name('kerma.ambilFile');
    });
    Route::resource('kerma', 'KermaController');    
    
    # MoU
    Route::group([ 'prefix' => 'mou'], function () {
        Route::get('data', 'MouController@data')->name('mou.data');
        Route::get('dataCountry', 'MouController@dataCountry')->name('mou.dataCountry');
    });
    Route::resource('mou', 'MouController');    
   
    # MoA
    Route::group([ 'prefix' => 'moa'], function () {
        Route::get('data', 'MoaController@data')->name('moa.data');
        Route::get('dataCountry', 'MoaController@dataCountry')->name('moa.dataCountry');

    });
    Route::resource('moa', 'MoaController');     
    
    # Rincian Kerjasama
    Route::group([ 'prefix' => 'rinciankerma'], function () {
        Route::get('data', 'RinciankermaController@data')->name('rinciankerma.data');
        Route::get('data_sub/{idSub}', 'RinciankermaController@data_sub')->name('rinciankerma.data_sub');
        Route::get('ambil_sub_by_bidang/{idSub}', 'RinciankermaController@ambil_sub')->name('rinciankerma.ambil_sub');
        Route::get('{rinciankerma}/delete', 'RinciankermaController@destroy')->name('rinciankerma.delete');
    });
    Route::resource('rinciankerma', 'RinciankermaController');
    
    # Rincian Sub Kerjasama
    Route::group([ 'prefix' => 'rincian-subkerjasama'], function () {
        Route::get('data', 'RinciansubkermaController@data')->name('rincian-subkerjasama.data');
        Route::get('{rinciansubkerjasama}/delete', 'RinciansubkermaController@destroy')->name('rincian-subkerjasama.delete');
        Route::get('ambilFile/{idrincian}', 'RinciansubkermaController@ambilFile')->name('rincian-subkerjasama.ambilFile');
    });
    Route::resource('rincian-subkerjasama', 'RinciansubkermaController');
    
    # Mahasiswa
    Route::group([ 'prefix' => 'mahasiswa'], function () {
        Route::get('data', 'MahasiswaController@data')->name('mahasiswa.data');
        Route::get('data_wisuda', 'MahasiswaController@data_wisuda')->name('mahasiswa.data_wisuda');
        Route::get('data_sex/{sex}', 'MahasiswaController@data_sex')->name('mahasiswa.data_sex');
        Route::get('data_status/{status}', 'MahasiswaController@data_status')->name('mahasiswa.data_status');
        Route::get('{mahasiswa}/delete', 'MahasiswaController@destroy')->name('mahasiswa.delete');
        Route::get('ambilFile/{mahasiswa}', 'MahasiswaController@ambilFile')->name('mahasiswa.ambilFile');
    });
    Route::resource('mahasiswa', 'MahasiswaController');
    
    # Tamu
    Route::group([ 'prefix' => 'tamu'], function () {
        Route::get('data', 'TamuController@data')->name('tamu.data');
        Route::get('{tamu}/delete', 'TamuController@destroy')->name('tamu.delete');
        Route::get('ambilFile/{tamu}', 'TamuController@ambilFile')->name('tamu.ambilFile');
    });
    Route::resource('tamu', 'TamuController');

             
    // route::get('test_email', function(){

    //     $data = "test permit";
    
    //     // Send the activation code through email
    //     Mail::to('portal.senuju@gmail.com')
    //         ->send(new notifPermit('dasdad'));
    // });
    
  

    // route::get('test_api_mahasiswa_status', function(){
    //     return api_mahasiswa_asing_status();
    // });
    
    // route::get('test_api_mahasiswa_aktif_all', function(){
    //     return mahasiswa_aktif_all();
    // });
    
    // route::get('test_api_fakultas', function(){
    //     return api_fakultas();
    // });
    
    // route::get('test_api_prodi', function(){
    //     return api_prodi();
    // });

app/SubBidang.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SubBidang extends Model
{
    // protected $table = 'sub_bidangs';
	protected $fillable = ['id','bidang_id','namaSubBidang', 'created_at'];

    protected $guarded = ['id'];

    public function bidang()
    {
        return $this->belongsTo('App\Bidang');
    }  
    
    public function rincianSubKerma()
    {
        return $this->hasMany('App\RincianSubKerma');
    }
}

app/Http/Controllers/Admin/SubbidangController.php
<?php

namespace App\Http\Controllers\Admin;

use\App\Http\Controllers\JoshController;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\SubbidangRequest;
use App\Bidang;
use App\SubBidang;
use File;
use Hash;
use Illuminate\Support\Facades\Mail;
use Redirect;
use Sentinel;
use URL;
use View;
use Yajra\DataTables\DataTables;
use Validator;
Use App\Mail\Restore;
use stdClass;
use DB;

class SubbidangController extends JoshController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Grab all the bidang
        $bidangs = Bidang::all();
        // Show the page
        return view('admin.subbidang.index', compact('bidangs'));
    }

    public function data()
    {
        // $subbidangs = SubBidang::get(['id','bidang_id', 'namaSubBidang','created_at']);
        DB::statement(DB::raw('set @rownum=0'));                
        $subbidangs = SubBidang::select([DB::raw('@rownum  := @rownum  + 1 AS rownum'),'id','bidang_id', 'namaSubBidang','created_at'])->orderBy('id', 'DESC')->get();
        return DataTables::of($subbidangs)
            ->editColumn('created_at',function(SubBidang $subbidangs) {
                return $subbidangs->created_at->diffForHumans();
            })
 
            ->addColumn('actions',function($subbidangs) {
                $actions = '<a onclick="showForm('.$subbidangs->id.')"><i class="livicon clearCacheForm" data-name="info" data-size="18" data-loop="true" data-c="#428BCA" data-hc="#428BCA" title="view subbidang"></i></a>
                            <a onclick="editForm('.$subbidangs->id.')"><i class="livicon clearCacheForm" data-name="edit" data-size="18" data-loop="true" data-c="#428BCA" data-hc="#428BCA" title="update subbidang"></i></a>';
                $actions .= '<a onclick="deleteForm('.$subbidangs->id.')"><i class="livicon" data-name="remove" data-size="18" data-loop="true" data-c="#f56954" data-hc="#f56954" title="delete subbidang"></i></a>';
              
                return $actions;
            })
            ->addColumn('bidang',function($subbidangs) {          
                return $subbidangs->bidang->namaBidang;
            })
            ->rawColumns(['actions','bidang'])
            ->make(true);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function show($id)
    {
        $subbidangs = SubBidang::where('id',$id)->first();    
        return json_encode($subbidangs);
    }

    
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store(SubBidangRequest $request)
    {

        $subbidangs = new SubBidang($request->all());

        if ($subbidangs->save()) {
            return json_encode($subbidangs);
        }
         else {
            return Redirect::route('admin.subbidang')->withInput()->with('error', 'Gagal menyimpan data');
        }
    }


    public function edit($subbidangs)
    {
        
    }

    public function update(SubbidangRequest $request, $id)
    {

        $subbidangs = SubBidang::find($id);
        if ($subbidangs->update($request->all())) {
            return json_encode($subbidangs);
        } else {
            return Redirect::route('admin/subbidang')->withInput()->with('error', trans('subbidang/message.error.update'));
        }
    }

    public function destroy($id)
    {
        $subbidangs = SubBidang::find($id);
        if ($subbidangs->delete()) {
            return json_encode($subbidangs);
        } else {
            return Redirect::route('admin/subbidang')->withInput()->with('error', trans('subbidang/message.error.delete'));
        }
    }
}

resources/views/admin/subbidang/ajax.blade.php
<script>
var table;
$(function() {
    table = $('#table').DataTable({ 
        processing: true,
        serverSide: true,
        ajax: '{!! route('admin.subbidang.data') !!}',
        columns: [
            { data: 'rownum' },
            { data: 'bidang', name: 'bidang' },
            { data: 'namaSubBidang', name: 'namaSubBidang' },
            { data: 'created_at', name:'created_at'},
            { data: 'actions', name: 'actions', orderable: false, searchable: false }
        ]
    });
    table.on( 'draw', function () {
        $('.livicon').each(function(){
            $(this).updateLivicon();
        });
    } );
});

    
// OPEN MODAL ADD
function addForm(){
    save_method="add";
    $('input[name=_method]').val('POST');
    $('#addModal').modal('show');
    $('#addModal form')[0].reset();
    $('#addModal .modal-title').text('Create Sub Bidang');
    $('.btnSave').removeClass('hide');

    $("body").on("click",".clearCacheForm",function(){ 
            $(".refresh").empty(); 
            $(".refresh").attr('readonly',false); 
    });

}

//OPEN MODAL EDIT
function editForm(id){
    save_method = "editSubSubBidang";
    $('input[name=_method]').val('PUT');
    $('#addModal').modal('show');
    $('#addModal form')[0].reset();
    $('#addModal .modal-title').text('Edit Sub Bidang');
    $('.btnSave').removeClass('hide');
    $("body").on("click",".clearCacheForm",function(){ 
            $(".refresh").empty(); 
            $(".refresh").attr('readonly',false); 
    });
    $.ajax({
        url: "{{ url('admin/subbidang') }}"+'/'+id,
        type: "GET",
        dataType: "JSON",
        success: function(data) {
                $('#idSubBidang').val(data.id);
                $("#bidang_id option[value='" + data.bidang_id + "']").prop("selected", true).change();
                $("#namaSubBidang").val(data.namaSubBidang);

        },
        error: function() {
            alert('Data is empty !')
        }
    });
};

//OPEN MODAL SHOW
function showForm(id){
    $('#addModal').modal('show');
    $('#addModal form')[0].reset();
    $('#addModal .modal-title').text('Show Sub Bidang');
    $('.btnSave').addClass('hide');

    $.ajax({
        url: "{{ url('admin/subbidang') }}"+'/'+id,
        type: "GET",
        dataType: "JSON",
        success: function(data) {
                $('#idSubBidang').val(data.id);
                $("#bidang_id option[value='" + data.bidang_id + "']").prop("selected", true).change();
                $("#namaSubBidang").val(data.namaSubBidang).attr('readonly', true);
        },
        error: function() {
            alert('Data is empty !')
        }
    });
};


//OPEN MODAL DELETE
function deleteForm(id){
    $('#delete_confirm').modal('show');
    $('#delete_confirm form')[0].reset();
    $('#delete_confirm .modal-title').text('Delete Sub Bidang');

    $.ajax({
        url: "{{ url('admin/subbidang') }}"+'/'+id,
        type: "GET",
        dataType: "JSON",
        success: function(data) {
                $('#idSubBidang').val(data.id);
                $("#pesan_hapus").text(data.namaSubBidang);
           
        },
        error: function() {
            alert('Data is empty !')
        }
    });
};

$('#delete_confirm form').on('submit', function(e){
    if (!e.isDefaultPrevented()){
            var id=$('#idSubBidang').val();

            url = "{{ url('admin/subbidang/') }}/"+id+"/delete";
          
            $.ajax({
            
                url : url,
                type : "GET",
                dataType: "JSON",
                success : function(syabdan){
                
                swal({
                        title: 'Success',
                        text: "Berhasil menghapus data",
                        type: 'success',
                        timer: 2000
                    });
                    
                        $('#delete_confirm').modal('hide');
                        table.ajax.reload();
                
                },
                error : function(syabdan){
                    swal({
                        title: 'Terjadi Kesalahan!',
                        text: "Gagal Menghapus data",
                        type: 'error',
                        timer: 2000
                    });
                    // alert("Tidak dapat menyimpan data!");
                }
            });
            return false;
        }
});
// End DELETE Function
    
$(function () {
	$('body').on('hidden.bs.modal', '.modal', function () {
		$(this).removeData('bs.modal');
	});
});

$('#addModal form').on('submit', function(e){
    if (!e.isDefaultPrevented()){
            var id=$('#idSubBidang').val();
        
            if(save_method=="add"){
            url = "{{ route('admin.subbidang.store') }}";
            } 
            else {
            url = "{{ url('admin/subbidang') }}"+'/'+id;
            } 
        
            var inputData = new FormData($(this)[0]);
            $.ajax({
            
                url : url,
                type : "POST",
                enctype: 'multipart/form-data',
                data : inputData,
            //  data: $('#addModal form').serialize(),
                beforeSend: function() {
                        $('.btnSave').attr('disabled', true);
                        $('.btnSave').html('<i class="fa fa-gear"></i> Prosessing ... ');
                },
                complete: function() {
                    $('.btnSave').attr('disabled', false);
                    $('.btnSave').html('<i class="fa fa-save"></i> Save');
                },
                processData: false,
                contentType: false,
                cache: false,
                dataType: "JSON",
                success : function(syabdan){
                
                swal({
                        title: 'Success',
                        text: "Berhasil menyimpan data",
                        type: 'success',
                        timer: 2000
                    });
                    $('.btnSave').attr('disabled', false);
                    $('.btnSave').html('<i class="fa fa-save"></i> Save');
                    $('#addModal').modal('hide');
                    table.ajax.reload();
                
                },
                error : function(syabdan){
                    swal({
                        title: 'Terjadi Kesalahan!',
                        text: "Gagal Menyimpan data",
                        type: 'error',
                        timer: 2000
                    });
                    if(syabdan['responseJSON']['errors']) {
                            if(syabdan['responseJSON']['errors']['namaSubBidang']){
                                $( '#namaSubBidangError' ).html(syabdan['responseJSON']['errors']['namaSubBidang'][0]);
                            }

                          
                    }
                    // alert("Tidak dapat menyimpan data!");
                }
            });
            return false;
        }
});



</script>

resources/views/admin/subbidang/index.blade.php
@extends('admin/layouts/default')

{{-- Page title --}}
@section('title')
Sub Bidangs List
@parent
@stop

{{-- page level styles --}}
@section('header_styles')
<link rel="stylesheet" type="text/css" href="{{ asset('assets/vendors/datatables/css/dataTables.bootstrap.css') }}" />
<link href="{{ asset('assets/css/pages/tables.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('assets/vendors/select2/css/select2.min.css') }}" type="text/css" rel="stylesheet">
<link href="{{ asset('assets/vendors/select2/css/select2-bootstrap.css') }}" rel="stylesheet">
@stop


{{-- Page content --}}
@section('content')
<section class="content-header">
    <h1>Sub Bidang</h1>
    <ol class="breadcrumb">
        <li>
            <a href="{{ route('admin.dashboard') }}">
                <i class="livicon" data-name="home" data-size="14" data-color="#000"></i>
                Dashboard
            </a>
        </li>
        <li><a href="#">Sub Bidang</a></li>
        <li class="active">Sub Bidang List</li>
    </ol>
</section>


<!-- Main content -->
<section class="content paddingleft_right15">
    <div class="row">
        <div class="panel panel-primary ">
            <div class="panel-heading clearfix">
                <h4 class="panel-title pull-left"> <i class="livicon" data-name="user" data-size="16" data-loop="true" data-c="#fff" data-hc="white"></i>
                   Sub Bidang List
                </h4>
                <div class="pull-right">
                    <a onclick="addForm()" class="btn btn-sm btn-default clearCacheForm"><span class="glyphicon glyphicon-plus"></span> @lang('button.create')</a>
                </div>
            </div>
            <br />
            <div class="panel-body">
                <div class="table-responsive">
                <table class="table table-bordered " id="table">
                    <thead>
                        <tr class="filters">
                            <th>No</th>
                            <th>Bidang</th>
                            <th>Sub Bidang</th>
                            <th>Created At</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>


                    </tbody>
                </table>
                </div>
            </div>
        </div>
    </div>    <!-- row-->
</section>
<div class="modal fade" id="delete_confirm"  role="dialog"  aria-hidden="true">
	<div class="modal-dialog">
    	<div class="modal-content">
        <div class="modal-header bg-blue">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"></h4>
        </div>
        <form data-toggle="validator" method="DELETE" enctype="multipart/form-data" class="form-horizontal">
        <input type="hidden" name="_token" value="{{ csrf_token() }}" />
        <input type="hidden" name="_method"  />

            <div class="modal-body">
                <div class="row">
                    Apakah Anda yakin untuk menghapus <b id="pesan_hapus"></b> ?
                    
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger " data-dismiss="modal"><i class="fa fa-times"></i>Nanti Saja</button>
                        <button type="submit" class="btn btn-primary pull-right" id="btnSave"><i class="fa fa-save"></i>   Hapus</button>
                    </div>
                </div>
            </div>
        </form>

        </div>
  </div>
</div>
<div class="modal fade" id="addModal"  role="dialog"  aria-hidden="true" data-backdrop="static" data-keyboard="false">
	<div class="modal-dialog">
    	<div class="modal-content">
        <div class="modal-header bg-blue">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title"></h4>
        </div>
        <form data-toggle="validator" method="PUT" enctype="multipart/form-data" class="form-horizontal">
        <input type="hidden" name="_token" value="{{ csrf_token() }}" />
        <input type="hidden" name="_method"  />

            <div class="modal-body">
                <div class="form-group {{ $errors->first('bidang_id', 'has-error') }}">
                    <label for="email" class="col-sm-3 control-label">Bidang *</label>
                    <div class="col-sm-9">
                        <select class="form-control select2" title="Select Bidang..." name="bidang_id" id="bidang_id" style="width: 100%;">
                        <option value="">Select Bidang ... </option>
                           @foreach($bidangs as $bidang)
                            <option value="{{ $bidang->id }}"
                                    @if(old('bidang_id') === '{{ $bidang->id }}' ) selected="selected" @endif >{{ $bidang->namaBidang}}
                            </option>
                           @endforeach

                        </select>
                    </div>
                    <span class="help-block">{{ $errors->first('bidang_id', ':message') }}</span>
                </div>
               
                <div class="form-group {{ $errors->first('namaSubBidang', 'has-error') }}">
                <label for="namaSubBidang" class="col-sm-3 control-label">Sub Bidang *</label>
                    <div class="col-sm-9">
                        <input type="text" id="namaSubBidang" name="namaSubBidang" class="form-control refresh" placeholder="Nama Sub Bidang" value="{!! old('namaSubBidang') !!}">
                        <span style="color: red;"><i><p id="namaSubBidangError"></p></i></span>
                    </div>
                    <input type="hidden" id="idSubBidang" name="idSubBidang" class="form-control refresh">
                    {!! $errors->first('namaSubBidang', '<span class="help-block">:message</span>') !!}
                
                </div>

               
                <div class="modal-footer">
					<button type="button" class="btn btn-danger " data-dismiss="modal"><i class="fa fa-times"></i>@lang('button.cancel')</button>
					<button type="submit" class="btn btn-primary pull-right btnSave" id="btnSave"><i class="fa fa-save"></i>   @lang('button.save')</button>
				</div>
            </div>
        </form>

        </div>
  </div>
</div>
@stop

{{-- page level scripts --}}
@section('footer_scripts')
    <script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/jquery.dataTables.js') }}" ></script>
    <script type="text/javascript" src="{{ asset('assets/vendors/datatables/js/dataTables.bootstrap.js') }}" ></script>
    <script src="{{ asset('assets/vendors/select2/js/select2.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/vendors/sweetalert/js/sweetalert.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/vendors/sweetalert/js/sweetalert-dev.js') }}" type="text/javascript"></script>
    <script src="{{ asset('assets/js/pages/custom_sweetalert.js') }}" type="text/javascript"></script>

@include('admin.subbidang.ajax')



@stop