routes/web.php
<?php
 use App\Mail\NotifikasiPermit; 
include_once 'web_builder.php';
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('nonaktif_permit', function () {
    \Artisan::call('nonaktif:permit');
});
Route::get('nonaktif_kerma', function () {
    \Artisan::call('nonaktif:kerma');
});
Route::get('sendnotif_permit', function () {
    \Artisan::call('send:NotifPermit');
});
Route::get('insert_mahasiswa', function () {
    \Artisan::call('insert:mahasiswa');
});


Route::pattern('slug', '[a-z0-9- _]+');

Route::group(['prefix' => 'admin', 'namespace'=>'Admin'], function () {

    # Error pages should be shown without requiring login
    Route::get('404', function () {
        return view('admin/404');
    });
    Route::get('500', function () {
        return view('admin/500');
    });

    # Lock screen
    Route::get('{id}/lockscreen', 'UsersController@lockscreen')->name('lockscreen');
    Route::post('{id}/lockscreen', 'UsersController@postLockscreen')->name('lockscreen');
    # All basic routes defined here
    Route::get('login', 'AuthController@getSignin')->name('login');
    Route::get('signin', 'AuthController@getSignin')->name('signin');
    Route::post('signin', 'AuthController@postSignin')->name('postSignin');
    Route::post('signup', 'AuthController@postSignup')->name('admin.signup');
    Route::post('forgot-password', 'AuthController@postForgotPassword')->name('forgot-password');

    # Forgot Password Confirmation
    Route::get('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm')->name('forgot-password-confirm');
    Route::post('forgot-password/{userId}/{passwordResetCode}', 'AuthController@getForgotPasswordConfirm');

    #Update Permit Status -> Dalam Pengurusan Permit
    Route::get('update-permit/{npm}/{noPermit}', 'PermitController@getUpdatePermitConfirm')->name('update-permit-confirm');

    # Logout
    Route::get('logout', 'AuthController@getLogout')->name('logout');

    # Account Activation
    Route::get('activate/{userId}/{activationCode}', 'AuthController@getActivate')->name('activate');
});


Route::group(['prefix' => 'admin',  'as' => 'admin.'], function () {
    # Dashboard / Index
    Route::get('/dashboard', 'JoshController@showHome')->name('dashboard');

});

Route::group(['prefix' => 'admin','namespace'=>'Admin', 'as' => 'admin.'], function () {
    
    Route::group(['middleware' => 'superadmin'], function () {

        # User Management
        Route::group([ 'prefix' => 'users'], function () {
            Route::get('data', 'UsersController@data')->name('users.data');
            Route::get('{user}/delete', 'UsersController@destroy')->name('users.delete');
            Route::get('{user}/confirm-delete', 'UsersController@getModalDelete')->name('users.confirm-delete');
            Route::get('{user}/restore', 'UsersController@getRestore')->name('restore.user');
            Route::post('{user}/passwordreset', 'UsersController@passwordreset')->name('passwordreset');
            Route::post('passwordreset', 'UsersController@passwordreset')->name('passwordreset');

        });
        Route::resource('users', 'UsersController');

        Route::get('deleted_users',['before' => 'Sentinel', 'uses' => 'UsersController@getDeletedUsers'])->name('deleted_users');

        # Group Management
        Route::group(['prefix' => 'groups'], function () {
            Route::get('{group}/delete', 'GroupsController@destroy')->name('groups.delete');
            Route::get('{group}/confirm-delete', 'GroupsController@getModalDelete')->name('groups.confirm-delete');
            Route::get('{group}/restore', 'GroupsController@getRestore')->name('groups.restore');
        });
        Route::resource('groups', 'GroupsController');

        # Master Bidang
        Route::group([ 'prefix' => 'bidang'], function () {
            Route::get('data', 'BidangController@data')->name('bidang.data');
            Route::get('{bidang}/delete', 'BidangController@destroy')->name('bidang.delete');
        });
        Route::resource('bidang', 'BidangController');
        
        # Master Subbidang
        Route::group([ 'prefix' => 'subbidang'], function () {
            Route::get('data', 'SubbidangController@data')->name('subbidang.data');
            Route::get('{subbidang}/delete', 'SubbidangController@destroy')->name('subbidang.delete');
        });
        Route::resource('subbidang', 'SubbidangController');
        
        # Master Unit
        Route::group([ 'prefix' => 'unit'], function () {
            Route::get('data', 'UnitController@data')->name('unit.data');
            Route::get('{unit}/delete', 'UnitController@destroy')->name('unit.delete');
        });
        Route::resource('unit', 'UnitController');
        


    });
Route::resource('users', 'UsersController');

// Route::group(['middleware' => ['superadmin']], function () {   // Diedit 15-04-2020
    # Laporan Kerjasama
    Route::group([ 'prefix' => 'laporan_kerma'], function () {
        Route::get('data', 'LaporanKermaController@data')->name('laporan_kerma.data');
        Route::get('{laporan_kerma}/delete', 'LaporanKermaController@destroy')->name('laporan_kerma.delete');
        Route::get('data_laporan/{tahun}/{bulan}/{negara}', 'LaporanKermaController@dataLaporan')->name('laporan_kerma.dataLaporan');
        Route::post('data_laporan', 'LaporanKermaController@cetakLaporan')->name('laporan_kerma.cetakLaporan');
    });
    Route::resource('laporan_kerma', 'LaporanKermaController');    

    # Laporan Mahasiswa
    Route::group([ 'prefix' => 'laporan_mahasiswa'], function () {
        Route::get('data', 'LaporanMahasiswaController@data')->name('laporan_mahasiswa.data');
        Route::get('{laporan_mahasiswa}/delete', 'LaporanMahasiswaController@destroy')->name('laporan_mahasiswa.delete');
        Route::get('data_laporan/{tahun}/{bulan}/{negara}', 'LaporanMahasiswaController@dataLaporan')->name('laporan_mahasiswa.dataLaporan');
        Route::post('data_laporan', 'LaporanMahasiswaController@cetakLaporan')->name('laporan_mahasiswa.cetakLaporan');
    });
    Route::resource('laporan_mahasiswa', 'LaporanMahasiswaController');
// });

    # Permit
    Route::group([ 'prefix' => 'permit'], function () {
        Route::get('data', 'PermitController@data')->name('permit.data');
        Route::get('get_mahasiswa/{npm}', 'PermitController@getMahasiswa')->name('permit.get_mahasiswa');
        Route::get('{permit}/delete', 'PermitController@destroy')->name('permit.delete');
        Route::get('ambilFile/{permit}', 'PermitController@ambilFile')->name('permit.ambilFile');
        Route::get('data_status/{status}', 'PermitController@data_status')->name('permit.data_status');

    });
    Route::resource('permit', 'PermitController');
    
    # Kerjasama
    Route::group([ 'prefix' => 'kerma'], function () {
        Route::get('data', 'KermaController@data')->name('kerma.data');
        Route::get('data_status/{status}', 'KermaController@data_status')->name('kerma.data_status');
        Route::get('{kerma}/delete', 'KermaController@destroy')->name('kerma.delete');
        Route::get('ambilFile/{kerma}', 'KermaController@ambilFile')->name('kerma.ambilFile');
    });
    Route::resource('kerma', 'KermaController');    
    
    # MoU
    Route::group([ 'prefix' => 'mou'], function () {
        Route::get('data', 'MouController@data')->name('mou.data');
        Route::get('dataCountry', 'MouController@dataCountry')->name('mou.dataCountry');
    });
    Route::resource('mou', 'MouController');    
   
    # MoA
    Route::group([ 'prefix' => 'moa'], function () {
        Route::get('data', 'MoaController@data')->name('moa.data');
        Route::get('dataCountry', 'MoaController@dataCountry')->name('moa.dataCountry');

    });
    Route::resource('moa', 'MoaController');     
    
    # Rincian Kerjasama
    Route::group([ 'prefix' => 'rinciankerma'], function () {
        Route::get('data', 'RinciankermaController@data')->name('rinciankerma.data');
        Route::get('data_sub/{idSub}', 'RinciankermaController@data_sub')->name('rinciankerma.data_sub');
        Route::get('ambil_sub_by_bidang/{idSub}', 'RinciankermaController@ambil_sub')->name('rinciankerma.ambil_sub');
        Route::get('{rinciankerma}/delete', 'RinciankermaController@destroy')->name('rinciankerma.delete');
    });
    Route::resource('rinciankerma', 'RinciankermaController');
    
    # Rincian Sub Kerjasama
    Route::group([ 'prefix' => 'rincian-subkerjasama'], function () {
        Route::get('data', 'RinciansubkermaController@data')->name('rincian-subkerjasama.data');
        Route::get('{rinciansubkerjasama}/delete', 'RinciansubkermaController@destroy')->name('rincian-subkerjasama.delete');
        Route::get('ambilFile/{idrincian}', 'RinciansubkermaController@ambilFile')->name('rincian-subkerjasama.ambilFile');
    });
    Route::resource('rincian-subkerjasama', 'RinciansubkermaController');
    
    # Mahasiswa
    Route::group([ 'prefix' => 'mahasiswa'], function () {
        Route::get('data', 'MahasiswaController@data')->name('mahasiswa.data');
        Route::get('data_wisuda', 'MahasiswaController@data_wisuda')->name('mahasiswa.data_wisuda');
        Route::get('data_sex/{sex}', 'MahasiswaController@data_sex')->name('mahasiswa.data_sex');
        Route::get('data_status/{status}', 'MahasiswaController@data_status')->name('mahasiswa.data_status');
        Route::get('{mahasiswa}/delete', 'MahasiswaController@destroy')->name('mahasiswa.delete');
        Route::get('ambilFile/{mahasiswa}', 'MahasiswaController@ambilFile')->name('mahasiswa.ambilFile');
    });

app/Permit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Permit extends Model
{
    protected $fillable = ['id','npm','noPermit','tglDikeluarkan','tglBerakhir','dokumenPermit','status_permit', 'created_at','mahasiswaln_id','status_notif','token_notif','status_notif_2','status_sms','status_sms_2','status_cron_permit','unit_id'];

    protected $guarded = ['id'];

    public function mahasiswaln()
    {
        return $this->belongsTo('App\Mahasiswaln');
    } 
}

resources/views/admin/permit/ajax.blade.php
<script>
var table;
$(function() {
    table = $('#table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('admin.permit.data') !!}',
        columns: [
            // { data: 'rownum' },
            { data: 'mahasiswa', name: 'mahasiswa' },
            { data: 'unit', name: 'unit' },
            { data: 'noPermit', name: 'noPermit' },
            { data: 'tglDikeluarkan', name:'tglDikeluarkan'},
            { data: 'tglBerakhir', name:'tglBerakhir'},
            { data: 'sisa_waktu'},
            { data: 'file'},
            { data: 'status_permit', name:'status_permit'},
            @if(Sentinel::inRole('admin') || Sentinel::inRole('superadmin') || Sentinel::getUser()->unit_id == 111)
            { data: 'actions', name: 'actions', orderable: false, searchable: false }
            @endif
            
        ]
    });
    table.on( 'draw', function () {
        $('.livicon').each(function(){
            $(this).updateLivicon();
        });
    } );
});

// OPEN MODAL Sex
function StatusModal(status){
    $('#StatusModal').modal('show');
    $('#StatusModal .modal-title').text('Data Permit Aktif');
    if(status == 'H'){
        $('#StatusModal .modal-title').text('Data Permit Tidak Aktif');
    }

    $(function() {
        // Datatable untuk Kelamin
     $('#table_status').DataTable({
        processing: true,
        serverSide: true,
        responsive: true,
        bDestroy: true,
        ajax: '{!! url('admin/permit/data_status') !!}'+"/"+status,
        columns: [
            // { data: 'rownum' },
            { data: 'mahasiswa', name: 'mahasiswa' },
            { data: 'unit', name: 'unit' },
            { data: 'noPermit', name: 'noPermit' },
            { data: 'tglDikeluarkan', name:'tglDikeluarkan'},
            { data: 'tglBerakhir', name:'tglBerakhir'},
            { data: 'sisa_waktu'},
            { data: 'file'},
            { data: 'status_permit', name:'status_permit'},
            @if(Sentinel::inRole('admin') || Sentinel::inRole('superadmin') || Sentinel::getUser()->unit_id == 111)
            { data: 'actions', name: 'actions', orderable: false, searchable: false }
            @endif
           
        ],

    });
        
    });

}

// OPEN MODAL ADD
function addForm(){
    save_method="add";
    $('input[name=_method]').val('POST');
    $('#addModal').modal('show');
    $('#addModal form')[0].reset();
    $('#addModal .modal-title').text('Create Permit');
    $('.btnSave').removeClass('hide');

    $("body").on("click",".clearCacheForm",function(){ 
            $(".refresh").empty(); 
            $(".refresh").attr('readonly',false); 
    });

}

//OPEN MODAL EDIT
function editForm(id){
    save_method = "edit";
    $('input[name=_method]').val('PUT');
    $('#addModal').modal('show');
    $('#addModal form')[0].reset();
    $('#addModal .modal-title').text('Edit Permit');
    $("#dokumenPermit").attr('required',false); 

    $('.btnSave').removeClass('hide');
    $("body").on("click",".clearCacheForm",function(){ 
            $(".refresh").empty(); 
            $(".refresh").attr('readonly',false); 
    });
    $.ajax({
        url: "{{ url('admin/permit') }}"+'/'+id,
        type: "GET",
        dataType: "JSON",
        success: function(data) {

                $('#id').val(data.id);
                $("#npm option[value='" + data.npm + "']").prop("selected", true).change();
                $("#unit_id option[value='" + data.unit_id + "']").prop("selected", true).change();
                $("#noPermit").val(data.noPermit);
                $("#tglDikeluarkan").val(data.tglDikeluarkan);
                $("#tglBerakhir").val(data.tglBerakhir);
                // $("#dokumenPermit").val(data.dokumenPermit);
        
                if(data.status_permit == 1){

                    // document.getElementById('status_permit').attr("checked", true);
                    document.getElementById('status_permit').checked = true;
                }else{
                    document.getElementById('status_permit').attr("checked", false);
                    // document.getElementById('status_permit').checked = false;

                }
              

        },
        error: function() {
            alert('Data is empty !')
        }
    });
};

//OPEN MODAL SHOW
function showForm(id){
    $('#addModal').modal('show');
    $('#addModal form')[0].reset();
    $('#addModal .modal-title').text('Show Permit');
    $('.btnSave').addClass('hide');

    $.ajax({
        url: "{{ url('admin/permit') }}"+'/'+id,
        type: "GET",
        dataType: "JSON",
        success: function(data) {
                $('#id').val(data.id);
                $("#npm option[value='" + data.npm + "']").prop("selected", true).change();
                $("#jPendidikan option[value='" + data.jPendidikan + "']").prop("selected", true).change();
                $("#noPermit").val(data.noPermit).attr('readonly', true);
                $("#tglDikeluarkan").val(data.tglDikeluarkan).attr('readonly', true);
                $("#tglBerakhir").val(data.tglBerakhir).attr('readonly', true);
        },
        error: function() {
            alert('Data is empty !')
        }
    });
};


//OPEN MODAL DELETE
function deleteForm(id){
    $('#delete_confirm').modal('show');
    $('#delete_confirm form')[0].reset();
    $('#delete_confirm .modal-title').text('Delete permit');

    $.ajax({
        url: "{{ url('admin/permit') }}"+'/'+id,
        type: "GET",
        dataType: "JSON",
        success: function(data) {
                $('#id').val(data.id);
                $("#pesan_hapus").text(data.noPermit);
           
        },
        error: function() {
            alert('Data is empty !')
        }
    });
};

$('#delete_confirm form').on('submit', function(e){
    if (!e.isDefaultPrevented()){
            var id=$('#id').val();

            url = "{{ url('admin/permit/') }}/"+id+"/delete";
          
            $.ajax({
            
                url : url,
                type : "GET",
                dataType: "JSON",
                success : function(syabdan){
                
                swal({
                        title: 'Success',
                        text: "Berhasil menghapus data",
                        type: 'success',
                        timer: 2000
                    });
                    
                        $('#delete_confirm').modal('hide');
                        table.ajax.reload();
                
                },
                error : function(syabdan){
                    swal({
                        title: 'Terjadi Kesalahan!',
                        text: "Gagal Menghapus data",
                        type: 'error',
                        timer: 2000
                    });
                    // alert("Tidak dapat menyimpan data!");
                }
            });
            return false;
        }
});
// End DELETE Function
    
$(function () {
	$('body').on('hidden.bs.modal', '.modal', function () {
		$(this).removeData('bs.modal');
	});
});

$('#addModal form').on('submit', function(e){
    if (!e.isDefaultPrevented()){
            var id=$('#id').val();
        
            if(save_method=="add"){
            url = "{{ route('admin.permit.store') }}";
            } 
            else {
            url = "{{ url('admin/permit') }}"+'/'+id;
            } 
        
            var inputData = new FormData($(this)[0]);
            $.ajax({
            
                url : url,
                type : "POST",
                enctype: 'multipart/form-data',
                data : inputData,
            //  data: $('#addModal form').serialize(),
                beforeSend: function() {
                    $('.btnSave').attr('disabled', true);
                    $('.btnSave').html('<i class="fa fa-gear"></i> Prosessing ... ');
                },
                complete: function() {
                    $('.btnSave').attr('disabled', false);
                    $('.btnSave').html('<i class="fa fa-save"></i> Save');
                },
        
                // processing: '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading...</span> ',
                processData: false,
                contentType: false,
                cache: false,
                dataType: "JSON",
                success : function(syabdan){
                
                swal({
                        title: 'Success',
                        text: "Berhasil menyimpan data",
                        type: 'success',
                        timer: 2000
                    });
                    
                
                $('#addModal').modal('hide');
                table.ajax.reload();
                
                },
                error : function(syabdan){
                    swal({
                        title: 'Terjadi Kesalahan!',
                        text: "Gagal Menyimpan data",
                        type: 'error',
                        timer: 2000
                    });
                    if(syabdan['responseJSON']['errors']) {
                            if(syabdan['responseJSON']['errors']['npm']){
                                $( '#npmError' ).html(syabdan['responseJSON']['errors']['npm'][0]);
                            }
                            if(syabdan['responseJSON']['errors']['noPermit']){
                                $( '#noPermitError' ).html(syabdan['responseJSON']['errors']['noPermit'][0]);
                            }
                            if(syabdan['responseJSON']['errors']['tglDikeluarkan']){
                                $( '#tglDikeluarkanError' ).html(syabdan['responseJSON']['errors']['tglDikeluarkan'][0]);
                            }
                            if(syabdan['responseJSON']['errors']['tglBerakhir']){
                                $( '#tglBerakhirError' ).html(syabdan['responseJSON']['errors']['tglBerakhir'][0]);
                            }

                          
                    }
                    // alert("Tidak dapat menyimpan data!");
                }
            });
            return false;
        }
});

$('#npm').on('change',function(){
				var npm = $('#npm').val();
	
					$.ajax({
						type :'GET',
						url  :  "{{ url('admin/permit/get_mahasiswa') }}" + '/' + npm,
						dataType: "json",
						success:function(data)
						{
                            $("#mahasiswaln_id").val(data.id);
						}
					}); 
			
				  
			});


$(function () {
    $('.datepicker').datepicker({
    autoclose: true,
    todayHighlight: true,
    })
});

$(".select2").select2();
</script>